apm install autocomplete-modules
apm install autocomplete-paths
apm install editorconfig
apm install emmet
apm install file-icons
apm install highlight-selected
apm install language-babel
apm install linter
apm install linter-eslint
apm install linter-stylelint
apm install project-manager
apm install relative-numbers
apm install vim-mode-plus
